### ISSUE TITLE
01-Claim reward 시 다중 Validator에게 재위임 할 수있는 기능이 필요합니다.

### ISSUE THREAD

**Issue by wooqii** [HeesungB/no-bad-chihuahua#2]
단일 밸리데이터 재위임 기능만 있다보니 여러 밸리데이터에 분산 시켜놓은 Account에서는 온전히 기능을 사용할 수 없습니다. 

`(node:53618) UnhandledPromiseRejectionWarning: Error: Broadcasting transaction failed with code 18 (codespace: sdk). Log: invalid delegation amount: invalid request
    at StargateClient.broadcastTx (/Users/wooqii/Documents/no-bad-chihuahua/node_modules/@cosmjs/stargate/src/stargateclient.ts:382:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:53618) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:53618) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:53618) UnhandledPromiseRejectionWarning: Error: Broadcasting transaction failed with code 18 (codespace: sdk). Log: invalid delegation amount: invalid request
    at StargateClient.broadcastTx (/Users/wooqii/Documents/no-bad-chihuahua/node_modules/@cosmjs/stargate/src/stargateclient.ts:382:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by HeesungB** [comment]
이슈는 #7 해당 PR에서 해결되었습니다.
버그 이슈 리포트 해주셔서 감사합니다! 👍
